cache:
  key: "new_test"
  paths:
    - node_modules/


stages:
  - lint
  - test
  - build


before_script:
  - npm install


lint:
  stage: lint
  script:
    - npm run stylelint
    - npm run lint
  allow_failure: false


test:
  stage: test
  script:
    - npm run flow
    - npm run test:coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

build:
  stage: build
  script:
    - npm run build
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_TAG}"
    paths:
      - dist/

  only:
    - tags
  except:
    - dev

  allow_failure: false

