language: node_js

node_js:
    - "8.4.0"

cache:
    directories:
        - node_modules

install:
    - npm install

script:
    - npm run lint
    - npm run flow
    - npm run test:coveralls
    - npm run build
