language: node_js
node_js:
  - "4.2.6"
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - npm run lint
script:
  - npm run coveralls
  - npm run build
deploy:
  on: master
  provider: surge
  project: ./dist/
  domain: http://trigen.surge.sh
  skip_cleanup: true
